-- ============================================================================
-- IMPORT ALL UK COUNCILS FROM WORD DOCUMENT
-- ============================================================================
-- Generated: 2025-11-17T17:00:32.656Z
-- Source: Council Emails copy.doc
-- Total councils: 344
--
-- This migration populates organizations and departments tables with all
-- UK councils and their licensing department contact information.
-- ============================================================================

-- Insert organizations (councils)
INSERT INTO public.organizations (name, created_at, updated_at)
VALUES
  ('Aberdeen City Council', NOW(), NOW()),
  ('Allerdale Council', NOW(), NOW()),
  ('Amber Valley Borough Council', NOW(), NOW()),
  ('Anglesey Council', NOW(), NOW()),
  ('Arun District Council', NOW(), NOW()),
  ('Ashfield Council', NOW(), NOW()),
  ('Ashford Borough Council', NOW(), NOW()),
  ('Aylesbury Council', NOW(), NOW()),
  ('Barking & Dagenhamm Council', NOW(), NOW()),
  ('Barnet Council', NOW(), NOW()),
  ('Barnsley Council', NOW(), NOW()),
  ('Barrow Council', NOW(), NOW()),
  ('Basildon Council', NOW(), NOW()),
  ('Basingstoke Council', NOW(), NOW()),
  ('Bath and North Somerset Council', NOW(), NOW()),
  ('Bedford Borough Council', NOW(), NOW()),
  ('Bedfordshire (Central) Council', NOW(), NOW()),
  ('Bexley Council', NOW(), NOW()),
  ('Birmingham City Council', NOW(), NOW()),
  ('Blackburn Council', NOW(), NOW()),
  ('Blackpool Council', NOW(), NOW()),
  ('Bolsover Council', NOW(), NOW()),
  ('Bolton Council', NOW(), NOW()),
  ('Boston Council', NOW(), NOW()),
  ('Bournemouth Council', NOW(), NOW()),
  ('Bracknell Forest Council', NOW(), NOW()),
  ('Bradford Council', NOW(), NOW()),
  ('Braintree Council', NOW(), NOW()),
  ('Breckland Council', NOW(), NOW()),
  ('Brent Council', NOW(), NOW()),
  ('Bridgend Council', NOW(), NOW()),
  ('Brighton Council', NOW(), NOW()),
  ('Bristol Council', NOW(), NOW()),
  ('Broadland District Council', NOW(), NOW()),
  ('Broadlane Council', NOW(), NOW()),
  ('Bromley Council', NOW(), NOW()),
  ('Bromsgrove Council', NOW(), NOW()),
  ('Broxbourne Council', NOW(), NOW()),
  ('Broxtowe Council', NOW(), NOW()),
  ('Buckinghamshire Council', NOW(), NOW()),
  ('Burnley Council', NOW(), NOW()),
  ('Bury Council', NOW(), NOW()),
  ('Caerphilly Council', NOW(), NOW()),
  ('Calderdale Council', NOW(), NOW()),
  ('Cambridge Council', NOW(), NOW()),
  ('Camden Council', NOW(), NOW()),
  ('Cannock Chase Council', NOW(), NOW()),
  ('Canterbury Council', NOW(), NOW()),
  ('Cardiff Council', NOW(), NOW()),
  ('Carlisle Council', NOW(), NOW()),
  ('Carmarthenshire Council', NOW(), NOW()),
  ('Castlepoint B.C Council', NOW(), NOW()),
  ('Central Bedfordshire Council', NOW(), NOW()),
  ('Ceredigion Council', NOW(), NOW()),
  ('Charnwood Council', NOW(), NOW()),
  ('Chelmsford Council', NOW(), NOW()),
  ('Cheltenham Council', NOW(), NOW()),
  ('Cherwell Council', NOW(), NOW()),
  ('Cherwell District council', NOW(), NOW()),
  ('Cheshire East Council', NOW(), NOW()),
  ('Cheshire west & Chester Council', NOW(), NOW()),
  ('Chesterfield Council', NOW(), NOW()),
  ('Chiltern Council', NOW(), NOW()),
  ('Chorley Council', NOW(), NOW()),
  ('City of London Council', NOW(), NOW()),
  ('Cleveland and Redcar Council', NOW(), NOW()),
  ('Colchester Council', NOW(), NOW()),
  ('Conwy Borough Council', NOW(), NOW()),
  ('Cornwall Council', NOW(), NOW()),
  ('Corona virus email; Council', NOW(), NOW()),
  ('Cotswold District Council', NOW(), NOW()),
  ('Coventry Council', NOW(), NOW()),
  ('Craven Council', NOW(), NOW()),
  ('Crawley Council', NOW(), NOW()),
  ('Croydon Council', NOW(), NOW()),
  ('Dacorum Council', NOW(), NOW()),
  ('Darlington Council', NOW(), NOW()),
  ('Dartford Council', NOW(), NOW()),
  ('Denbighshire Council', NOW(), NOW()),
  ('Derby Council', NOW(), NOW()),
  ('Derbyshire (North East) Council', NOW(), NOW()),
  ('Derbyshire Council', NOW(), NOW()),
  ('Devon Council', NOW(), NOW()),
  ('Doncaster Council', NOW(), NOW()),
  ('Dover Council', NOW(), NOW()),
  ('Dudley Council', NOW(), NOW()),
  ('Dundee Council', NOW(), NOW()),
  ('Durham Council', NOW(), NOW()),
  ('Ealing Council', NOW(), NOW()),
  ('East Cambridgeshire Council', NOW(), NOW()),
  ('East Devon Council', NOW(), NOW()),
  ('East Dorset Council', NOW(), NOW()),
  ('East Hampshire District Council', NOW(), NOW()),
  ('East Hertfordshire District Council', NOW(), NOW()),
  ('East Lindsey Council', NOW(), NOW()),
  ('East Northamptonshire Council', NOW(), NOW()),
  ('East Riding Council', NOW(), NOW()),
  ('East Staffs Council', NOW(), NOW()),
  ('Eastbourne Council', NOW(), NOW()),
  ('Eastleigh Council', NOW(), NOW()),
  ('Eden District Council', NOW(), NOW()),
  ('Elmbridge Council', NOW(), NOW()),
  ('Enfield Council', NOW(), NOW()),
  ('Epping Forest Council', NOW(), NOW()),
  ('Epsom & Ewell Borough council', NOW(), NOW()),
  ('Erewash Council', NOW(), NOW()),
  ('Exeter Council', NOW(), NOW()),
  ('Fareham Council', NOW(), NOW()),
  ('Fenland Council', NOW(), NOW()),
  ('Flintshire Council', NOW(), NOW()),
  ('Forest Heath Council', NOW(), NOW()),
  ('Fylde Council', NOW(), NOW()),
  ('Gateshead Council', NOW(), NOW()),
  ('Gedling: Council', NOW(), NOW()),
  ('Glasgow City Council', NOW(), NOW()),
  ('Gloucester Council', NOW(), NOW()),
  ('Gosport Council', NOW(), NOW()),
  ('Gravesham Council', NOW(), NOW()),
  ('Great Yarmouth Council', NOW(), NOW()),
  ('Greenwich Council', NOW(), NOW()),
  ('Guildford Council', NOW(), NOW()),
  ('Gwent Council', NOW(), NOW()),
  ('Gwynedd Council', NOW(), NOW()),
  ('Hackney Council', NOW(), NOW()),
  ('Halton Borough Council', NOW(), NOW()),
  ('Hambleton District Council', NOW(), NOW()),
  ('Hammersmith & Fulham Council', NOW(), NOW()),
  ('Harborough', NOW(), NOW()),
  ('Haringey Council', NOW(), NOW()),
  ('Harlow Council', NOW(), NOW()),
  ('Harrogate Council', NOW(), NOW()),
  ('Harrow Council', NOW(), NOW()),
  ('Harrow: Council', NOW(), NOW()),
  ('Hart Council', NOW(), NOW()),
  ('Hartlepool Council', NOW(), NOW()),
  ('Hastings Council', NOW(), NOW()),
  ('Havant Borough Council', NOW(), NOW()),
  ('Havering (London Borough)', NOW(), NOW()),
  ('Herefordshire Council', NOW(), NOW()),
  ('Hertfordshire County Council', NOW(), NOW()),
  ('Hertsmere Council', NOW(), NOW()),
  ('High Peak Borough', NOW(), NOW()),
  ('Hillingdon (London Borough', NOW(), NOW()),
  ('Hinckley & Bosworth Council', NOW(), NOW()),
  ('Horsham District Council', NOW(), NOW()),
  ('Hounslow Council', NOW(), NOW()),
  ('Hull Council', NOW(), NOW()),
  ('Huntingdonshire District Council', NOW(), NOW()),
  ('Hyndburn Borough Council', NOW(), NOW()),
  ('HYPERLINK "mailto:H&CSLicensing@lbbd.gov.uk" H&CSLicensing@lbbd.gov.uk Council', NOW(), NOW()),
  ('HYPERLINK "mailto:licensing@copeland.gov.uk"Copeland Council', NOW(), NOW()),
  ('HYPERLINK "mailto:licensing@hounslow.gov.uk" Council', NOW(), NOW()),
  ('Inverclyde Council', NOW(), NOW()),
  ('Ipswich Council', NOW(), NOW()),
  ('Isle of Wight Council', NOW(), NOW()),
  ('Islington Council', NOW(), NOW()),
  ('Kensington & Chelsea Council', NOW(), NOW()),
  ('Kettering Council', NOW(), NOW()),
  ('Kings Lynn & Norfolk Council', NOW(), NOW()),
  ('Kingston Upon Thames Council', NOW(), NOW()),
  ('Kirklees Council', NOW(), NOW()),
  ('Knowsley Borough Council', NOW(), NOW()),
  ('Lambeth Council', NOW(), NOW()),
  ('Lancaster Council', NOW(), NOW()),
  ('Leeds Council', NOW(), NOW()),
  ('Leicester Council', NOW(), NOW()),
  ('Lewes Council', NOW(), NOW()),
  ('Lewisham (London Borough of)', NOW(), NOW()),
  ('Lichfield Council', NOW(), NOW()),
  ('Lincoln Council', NOW(), NOW()),
  ('Liverpool Council', NOW(), NOW()),
  ('London Borough of Merton', NOW(), NOW()),
  ('London Borough of Sutton', NOW(), NOW()),
  ('Luton Council', NOW(), NOW()),
  ('Maidstone Council', NOW(), NOW()),
  ('Malden Council', NOW(), NOW()),
  ('Malvern Hills Council', NOW(), NOW()),
  ('Manchester Council', NOW(), NOW()),
  ('Mansfield Council', NOW(), NOW()),
  ('Medway Council', NOW(), NOW()),
  ('Melton Council', NOW(), NOW()),
  ('Mendip District Council', NOW(), NOW()),
  ('Mid Devon District Council', NOW(), NOW()),
  ('Mid Suffolk Council', NOW(), NOW()),
  ('Mid Sussex Council', NOW(), NOW()),
  ('Middlesbrough Council', NOW(), NOW()),
  ('Milton Keynes Council', NOW(), NOW()),
  ('Monmouthshire Council', NOW(), NOW()),
  ('Neath Port Talbot Council', NOW(), NOW()),
  ('New Forest Council', NOW(), NOW()),
  ('Newark & Sherwood Council', NOW(), NOW()),
  ('Newcastle Council', NOW(), NOW()),
  ('Newcastle under Lyme Borough Council', NOW(), NOW()),
  ('Newcastle under Lyme Council', NOW(), NOW()),
  ('Newham Council', NOW(), NOW()),
  ('Newport Council', NOW(), NOW()),
  ('North Devon Council', NOW(), NOW()),
  ('North Dorset Council', NOW(), NOW()),
  ('North East Lincolnshire Council', NOW(), NOW()),
  ('North East Lincs Council', NOW(), NOW()),
  ('North Hertfordshire Council', NOW(), NOW()),
  ('North Herts Council', NOW(), NOW()),
  ('North Kesteven: Council', NOW(), NOW()),
  ('North Lincolnshire Council', NOW(), NOW()),
  ('North Norfolk Council', NOW(), NOW()),
  ('North Somerset Council', NOW(), NOW()),
  ('North Tyneside Council', NOW(), NOW()),
  ('North Warwickshire Council', NOW(), NOW()),
  ('North West Council', NOW(), NOW()),
  ('North West Leicestershire Council', NOW(), NOW()),
  ('Northampton Council', NOW(), NOW()),
  ('Northumberland Council', NOW(), NOW()),
  ('Norwich Council', NOW(), NOW()),
  ('Nottingham Council', NOW(), NOW()),
  ('Oadby and Wigston Council', NOW(), NOW()),
  ('Oldham Council', NOW(), NOW()),
  ('Oxford Council', NOW(), NOW()),
  ('Pembrokeshire Council', NOW(), NOW()),
  ('Pendle Council', NOW(), NOW()),
  ('Peterborough', NOW(), NOW()),
  ('Plymouth Council', NOW(), NOW()),
  ('Portsmouth Council', NOW(), NOW()),
  ('Powys Council', NOW(), NOW()),
  ('Preston Council', NOW(), NOW()),
  ('Reading Council', NOW(), NOW()),
  ('Redbridge Council', NOW(), NOW()),
  ('Redcar & Cleveland Borough Council', NOW(), NOW()),
  ('Redditch Council', NOW(), NOW()),
  ('Reigate Council', NOW(), NOW()),
  ('Rhondda Council', NOW(), NOW()),
  ('Richmond Upon Thames (London Borough)', NOW(), NOW()),
  ('Richmondshire Council', NOW(), NOW()),
  ('Rochdale Council', NOW(), NOW()),
  ('Rochford Council', NOW(), NOW()),
  ('Rossendale Borough Council', NOW(), NOW()),
  ('Rotherham Council', NOW(), NOW()),
  ('Rugby Council', NOW(), NOW()),
  ('Runnymede Borough Council', NOW(), NOW()),
  ('Rushcliffe Borough Council', NOW(), NOW()),
  ('Rushmoor Council', NOW(), NOW()),
  ('Rutland County Council', NOW(), NOW()),
  ('Ryedale Council', NOW(), NOW()),
  ('Salford Council', NOW(), NOW()),
  ('Sandwell Council', NOW(), NOW()),
  ('Scarborough', NOW(), NOW()),
  ('Sedgemoor Council', NOW(), NOW()),
  ('Sefton Council', NOW(), NOW()),
  ('Selby Council', NOW(), NOW()),
  ('Sevenoaks Council', NOW(), NOW()),
  ('Sheffield Council', NOW(), NOW()),
  ('Shepway Council', NOW(), NOW()),
  ('Shropshire Council', NOW(), NOW()),
  ('Slough Council', NOW(), NOW()),
  ('Solihull Council', NOW(), NOW()),
  ('Somerset Council', NOW(), NOW()),
  ('South Bucks District Council', NOW(), NOW()),
  ('South Cambs District Council', NOW(), NOW()),
  ('South Derbyshire Council', NOW(), NOW()),
  ('South Gloucestershire Council', NOW(), NOW()),
  ('South Hams Council', NOW(), NOW()),
  ('South Holland Council', NOW(), NOW()),
  ('South Kesteven District Council', NOW(), NOW()),
  ('South Lakeland Council', NOW(), NOW()),
  ('South Lanarkshire Council', NOW(), NOW()),
  ('South Norfolk Council', NOW(), NOW()),
  ('South Northamptonshire Council', NOW(), NOW()),
  ('South Ribble Council', NOW(), NOW()),
  ('South Tyneside Council', NOW(), NOW()),
  ('Southampton Council', NOW(), NOW()),
  ('Southend on Sea Council', NOW(), NOW()),
  ('Southwark Council', NOW(), NOW()),
  ('Spelthorne Council', NOW(), NOW()),
  ('St Albans Council', NOW(), NOW()),
  ('St Edmundsbury Council', NOW(), NOW()),
  ('St Helens Council', NOW(), NOW()),
  ('Stafford Council', NOW(), NOW()),
  ('Staffordshire Moorlands Council', NOW(), NOW()),
  ('Stevenage Council', NOW(), NOW()),
  ('Stockport Council', NOW(), NOW()),
  ('Stockton Council', NOW(), NOW()),
  ('Stoke on Trent City Council', NOW(), NOW()),
  ('Stratford on Avon Council', NOW(), NOW()),
  ('Stroud Council', NOW(), NOW()),
  ('Suffolk Council', NOW(), NOW()),
  ('Sunderland Council', NOW(), NOW()),
  ('Swale Council', NOW(), NOW()),
  ('Swansea Council', NOW(), NOW()),
  ('Swindon Council', NOW(), NOW()),
  ('Tameside Council', NOW(), NOW()),
  ('Tamworth Council', NOW(), NOW()),
  ('Tandridge District Council', NOW(), NOW()),
  ('Taunton Council', NOW(), NOW()),
  ('Telford & Wrekin Council', NOW(), NOW()),
  ('Tendring Council', NOW(), NOW()),
  ('Tewsbury Council', NOW(), NOW()),
  ('Thanet Council', NOW(), NOW()),
  ('Thurrock Council', NOW(), NOW()),
  ('Tonbridge & Malling Council', NOW(), NOW()),
  ('Torbay Council', NOW(), NOW()),
  ('Torfaen (wales nr Pontypool) Council', NOW(), NOW()),
  ('Torridge Council', NOW(), NOW()),
  ('Tower Hamlets Council', NOW(), NOW()),
  ('Trafford Council', NOW(), NOW()),
  ('Uttlesford Council', NOW(), NOW()),
  ('Vale of Glamorgan Council', NOW(), NOW()),
  ('Vale of White Horse District Council', NOW(), NOW()),
  ('Wakefield Council', NOW(), NOW()),
  ('Walsall Council', NOW(), NOW()),
  ('Waltham Forest Council', NOW(), NOW()),
  ('Wandsworth Council', NOW(), NOW()),
  ('Warrington Council', NOW(), NOW()),
  ('Warwick Council', NOW(), NOW()),
  ('Watford Council', NOW(), NOW()),
  ('Waveney Council', NOW(), NOW()),
  ('Waverley Council', NOW(), NOW()),
  ('Wealden Council', NOW(), NOW()),
  ('Welwyn Council', NOW(), NOW()),
  ('West Berkshire Council', NOW(), NOW()),
  ('West Devon Council', NOW(), NOW()),
  ('West Dorset Council', NOW(), NOW()),
  ('West Lancashire Council', NOW(), NOW()),
  ('West Lindsey Council', NOW(), NOW()),
  ('West Oxfordshire Council', NOW(), NOW()),
  ('West Suffolk Council', NOW(), NOW()),
  ('West Sussex City Council', NOW(), NOW()),
  ('Westminster (City of) Council', NOW(), NOW()),
  ('Weymouth & Portland Council', NOW(), NOW()),
  ('Wigan Council', NOW(), NOW()),
  ('Wiltshire (4 diff offices, north, south, east, west) Council', NOW(), NOW()),
  ('Winchester 01962 848239 Council', NOW(), NOW()),
  ('Windsor & Maidenhead Council', NOW(), NOW()),
  ('Wirral Council', NOW(), NOW()),
  ('Woking Council', NOW(), NOW()),
  ('Wokingham Council', NOW(), NOW()),
  ('Wolverhampton Council', NOW(), NOW()),
  ('Worcester City Council', NOW(), NOW()),
  ('Worthing Council', NOW(), NOW()),
  ('Wrexham Council', NOW(), NOW()),
  ('Wychavon Council', NOW(), NOW()),
  ('Wycombe Council', NOW(), NOW()),
  ('Wycombe District Council', NOW(), NOW()),
  ('Wyre Borough Council', NOW(), NOW()),
  ('Wyre Forest District Council', NOW(), NOW()),
  ('York Council', NOW(), NOW())
ON CONFLICT (name) DO NOTHING;

-- Insert licensing departments for each council
INSERT INTO public.departments (organization_id, name, slug, type, email, created_at, updated_at)
SELECT
  o.id,
  'Licensing',
  'licensing',
  'licensing',
  d.email,
  NOW(),
  NOW()
FROM public.organizations o
CROSS JOIN (VALUES
  ('Aberdeen City Council', 'pi@aberdeen.gov.uk'),
  ('Allerdale Council', 'licensing@allerdale.gov.uk'),
  ('Amber Valley Borough Council', 'licensing@ambervalley.gov.uk'),
  ('Anglesey Council', 'licensing@anglesey.gov.uk'),
  ('Arun District Council', 'licensing@arun.gov.uk'),
  ('Ashfield Council', 'licensing@ashfield-dc.gov.uk'),
  ('Ashford Borough Council', 'licensing@ashford.gov.uk'),
  ('Aylesbury Council', 'licensing@aylesburyvaledc.gov.uk'),
  ('Barking & Dagenhamm Council', 'hcs.licensing@lbbd.gov.uk'),
  ('Barnet Council', 'michelle.rudland@barnet.gov.uk'),
  ('Barnsley Council', 'regulatoryservices@barnsley.gov.uk'),
  ('Barrow Council', 'commercial@barrowbc.gov.uk'),
  ('Basildon Council', 'mailroom@basildon.gov.uk'),
  ('Basingstoke Council', 'licensing@basingstoke.gov.uk'),
  ('Bath and North Somerset Council', 'licensing@bathnes.gov.uk'),
  ('Bedford Borough Council', 'Licensing@bedford.gov.uk'),
  ('Bedfordshire (Central) Council', 'licensing.section@centralbedfordshire.gov.uk'),
  ('Bexley Council', 'licensing.office@bexley.gov.uk'),
  ('Birmingham City Council', 'Licensing@birmingham.gov.uk'),
  ('Blackburn Council', 'licensing@blackburn.gov.uk'),
  ('Blackpool Council', 'licensing.la2003@blackpool.gov.uk'),
  ('Bolsover Council', 'licensing@bolsover.gov.uk'),
  ('Bolton Council', 'licensing.unit@bolton.gov.uk'),
  ('Boston Council', 'licensing@boston.gov.uk'),
  ('Bournemouth Council', 'Licensing@bournemouth.gov.uk'),
  ('Bracknell Forest Council', 'licence.all@bracknell-forest.gov.uk'),
  ('Bradford Council', 'licensingteam@bradford.gov.uk'),
  ('Braintree Council', 'licensing@braintree.gov.uk'),
  ('Breckland Council', 'licensingteam@breckland.gov.uk'),
  ('Brent Council', 'environmentandprotection@brent.gov.uk'),
  ('Bridgend Council', 'licensing@bridgend.gov.uk'),
  ('Brighton Council', 'ehl.safety@brighton-hove.gov.uk'),
  ('Bristol Council', 'licensing@bristol.gov.uk'),
  ('Broadland District Council', 'licensing@broadland.gov.uk'),
  ('Broadlane Council', 'environ.enforcement@broadland.gov.uk'),
  ('Bromley Council', 'licensing@bromley.gov.uk'),
  ('Bromsgrove Council', 'enquiries@worcsregservices.gov.uk'),
  ('Broxbourne Council', 'licensing@broxbourne.gov.uk'),
  ('Broxtowe Council', 'licensing@broxtowe.gov.uk'),
  ('Buckinghamshire Council', 'licensing@buckinghamshire.gov.uk'),
  ('Burnley Council', 'licensing@burnley.gov.uk'),
  ('Bury Council', 'licensing@bury.gov.uk'),
  ('Caerphilly Council', 'licensing@caerphilly.gov.uk'),
  ('Calderdale Council', 'licensing@calderdale.gov.uk'),
  ('Cambridge Council', 'licensing@cambridge.gov.uk'),
  ('Camden Council', 'licensing.safety@camden.gov.uk'),
  ('Cannock Chase Council', 'licensingunit@cannockchasedc.gov.uk'),
  ('Canterbury Council', 'envhealth@canterbury.gov.uk'),
  ('Cardiff Council', 'licensing@cardiff.gov.uk'),
  ('Carlisle Council', 'licensing@carlisle.gov.uk'),
  ('Carmarthenshire Council', 'direct@carmarthenshire.gov.uk'),
  ('Castlepoint B.C Council', 'licensingunit@castlepoint.gov.uk'),
  ('Central Bedfordshire Council', 'customer.services@centralbedfordshire.gov.uk'),
  ('Ceredigion Council', 'licensing@ceredigion.gov.uk'),
  ('Charnwood Council', 'licensing@charnwood.gov.uk'),
  ('Chelmsford Council', 'licensing@chelmsford.gov.uk'),
  ('Cheltenham Council', 'Licensing@cheltenham.gov.uk'),
  ('Cherwell Council', 'licensing@cherwell-dc.gov.uk'),
  ('Cherwell District council', 'licensing@cherwell-dc.gov.uk'),
  ('Cheshire East Council', 'licensing@cheshireeast.gov.uk'),
  ('Cheshire west & Chester Council', 'licensing2@cheshirewestandchester.gov.uk'),
  ('Chesterfield Council', 'licensing@chesterfield.gov.uk'),
  ('Chiltern Council', 'licensing@chiltern.gov.uk'),
  ('Chorley Council', 'contact@chorley.gov.uk'),
  ('City of London Council', 'Licensing@cityoflondon.gov.uk'),
  ('Cleveland and Redcar Council', 'licensingadmin@redcar-cleveland.gov.uk'),
  ('Colchester Council', 'customerservicecentre@colchester.gov.uk'),
  ('Conwy Borough Council', 'regulatory.services@conwy.gov.uk'),
  ('Cornwall Council', 'licensing@cornwall.gov.uk'),
  ('Corona virus email; Council', 'licensing@mansfield.gov.uk'),
  ('Cotswold District Council', 'licensing@cotswold.gov.uk'),
  ('Coventry Council', 'licensing@coventry.gov.uk'),
  ('Craven Council', 'environmentalhealth@cravendc.gov.uk'),
  ('Crawley Council', 'licensing@crawley.gov.uk'),
  ('Croydon Council', 'licensing@croydon.gov.uk'),
  ('Dacorum Council', 'licensing@dacorum.gov.uk'),
  ('Darlington Council', 'licensing@darlington.gov.uk'),
  ('Dartford Council', 'licensing@dartford.gov.uk'),
  ('Denbighshire Council', 'licensing@denbighshire.gov.uk'),
  ('Derby Council', 'licensing@derby.gov.uk'),
  ('Derbyshire (North East) Council', 'licensing@ne-derbyshire.gov.uk'),
  ('Derbyshire Council', 'licensing@derbyshiredales.gov.uk'),
  ('Devon Council', 'licensing@middevon.gov.uk'),
  ('Doncaster Council', 'licensing@doncaster.gov.uk'),
  ('Dover Council', 'licensing@dover.gov.uk'),
  ('Dudley Council', 'liquor.licensing@dudley.gov.uk'),
  ('Dundee Council', 'licensing.board@dundeecity.gov.uk'),
  ('Durham Council', 'licensing@durham.gov.uk'),
  ('Ealing Council', 'licensing@ealing.gov.uk'),
  ('East Cambridgeshire Council', 'licensing@eastcambs.gov.uk'),
  ('East Devon Council', 'licensing@eastdevon.gov.uk'),
  ('East Dorset Council', 'info@eastdorset.gov.uk'),
  ('East Hampshire District Council', 'licensing@easthants.gov.uk'),
  ('East Hertfordshire District Council', 'community.protection@eastherts.gov.uk'),
  ('East Lindsey Council', 'licensing@e-lindsey.gov.uk'),
  ('East Northamptonshire Council', 'licensingunit@east-northamptonshire.gov.uk'),
  ('East Riding Council', 'licensing@eastriding.gov.uk'),
  ('East Staffs Council', 'licensing@eaststaffsbc.gov.uk'),
  ('Eastbourne Council', 'licensing@eastbourne.gov.uk'),
  ('Eastleigh Council', 'liquor.licence@eastleigh.gov.uk'),
  ('Eden District Council', 'admin.licensing@eden.gov.uk'),
  ('Elmbridge Council', 'envhealth@elmbridge.gov.uk'),
  ('Enfield Council', 'licencing@enfield.gov.uk'),
  ('Epping Forest Council', 'licensing@eppingforestdc.gov.uk'),
  ('Epsom & Ewell Borough council', 'licensing@epsom-ewell.gov.uk'),
  ('Erewash Council', 'licensing@erewash.gov.uk'),
  ('Exeter Council', 'licensing.team@exeter.gov.uk'),
  ('Fareham Council', 'customerservices@fareham.gov.uk'),
  ('Fenland Council', 'licensing@fenland.gov.uk'),
  ('Flintshire Council', 'licensing@flintshire.gov.uk'),
  ('Forest Heath Council', 'licensing@forest-heath.gov.uk'),
  ('Fylde Council', 'licensing@fylde.gov.uk'),
  ('Gateshead Council', 'daniellines@gateshead.gov.uk'),
  ('Gedling: Council', 'licensing@gedling.gov.uk'),
  ('Glasgow City Council', 'LicensingBoard@ced.glasgow.gov.uk'),
  ('Gloucester Council', 'licence.team@gloucester.gov.uk'),
  ('Gosport Council', 'ehs@gosport.gov.uk'),
  ('Gravesham Council', 'licensing@gravesham.gov.uk'),
  ('Great Yarmouth Council', 'licensing@great-yarmouth.gov.uk'),
  ('Greenwich Council', 'licensing@royalgreenwich.gov.uk'),
  ('Guildford Council', '996licensing@guildford.gov.uk'),
  ('Gwent Council', 'licensing@blaenau-gwent.gov.uk'),
  ('Gwynedd Council', 'AledDavies@gwynedd.gov.uk'),
  ('Hackney Council', 'licensing@hackney.gov.uk'),
  ('Halton Borough Council', 'hdl@halton.gov.uk'),
  ('Hambleton District Council', 'licensingteam@hambleton.gov.uk'),
  ('Hammersmith & Fulham Council', 'licensing@lbhf.gov.uk'),
  ('Harborough', 'licensing@harborough.gov.uk'),
  ('Haringey Council', 'licensing@haringey.gov.uk'),
  ('Harlow Council', 'licensing@harlow.gov.uk'),
  ('Harrogate Council', 'licensing@harrogate.gov.uk'),
  ('Harrow Council', 'licensing@harrow.gov.uk'),
  ('Harrow: Council', 'licensing@harrow.gov.uk'),
  ('Hart Council', 'licensing@hart.gov.uk'),
  ('Hartlepool Council', 'licensing@hartlepool.gov.uk'),
  ('Hastings Council', 'licensing@hastings.gov.uk'),
  ('Havant Borough Council', 'licensing@havant.gov.uk'),
  ('Havering (London Borough)', 'licensing@havering.gov.uk'),
  ('Herefordshire Council', 'licensing@herefordshire.gov.uk'),
  ('Hertfordshire County Council', 'janet.shaw@hertfordshire.gov.uk'),
  ('Hertsmere Council', 'licensing@hertsmere.gov.uk'),
  ('High Peak Borough', 'customer-services@highpeak.gov.uk'),
  ('Hillingdon (London Borough', 'licensing@hillingdon.gov.uk'),
  ('Hinckley & Bosworth Council', 'esadmin@hinckley-bosworth.gov.uk'),
  ('Horsham District Council', 'licensing@horsham.gov.uk'),
  ('Hounslow Council', 'licensing@hounslow.gov.uk'),
  ('Hull Council', 'licensing.requests@hullcc.gov.uk'),
  ('Huntingdonshire District Council', 'licensing@huntingdonshire.gov.uk'),
  ('Hyndburn Borough Council', 'enquiries@hyndburnbc.gov.uk'),
  ('HYPERLINK "mailto:H&CSLicensing@lbbd.gov.uk" H&CSLicensing@lbbd.gov.uk Council', 'Licensing@lbbd.gov.uk'),
  ('HYPERLINK "mailto:licensing@copeland.gov.uk"Copeland Council', 'Licensing@Copeland.gov.uk'),
  ('HYPERLINK "mailto:licensing@hounslow.gov.uk" Council', 'shea@houslow.gov.uk'),
  ('Inverclyde Council', 'comments@inverclyde.gov.uk'),
  ('Ipswich Council', 'licensingandenforcement@ipswich.gov.uk'),
  ('Isle of Wight Council', 'licensing@iow.gov.uk'),
  ('Islington Council', 'licensing@islington.gov.uk'),
  ('Kensington & Chelsea Council', 'licensing@rbkc.gov.uk'),
  ('Kettering Council', 'licensing@kettering.gov.uk'),
  ('Kings Lynn & Norfolk Council', 'ehlicensing@west-norfolk.gov.uk'),
  ('Kingston Upon Thames Council', 'licensing@kingston.gov.uk'),
  ('Kirklees Council', 'licensing@kirklees.gov.uk'),
  ('Knowsley Borough Council', 'licensing@knowsley.gov.uk'),
  ('Lambeth Council', 'licensing@lambeth.gov.uk'),
  ('Lancaster Council', 'licensing@lancaster.gov.uk'),
  ('Leeds Council', 'entertainment.licensing@leeds.gov.uk'),
  ('Leicester Council', 'licensing@leicester.gov.uk'),
  ('Lewes Council', 'ehealth@lewes.gov.uk'),
  ('Lewisham (London Borough of)', 'licensing@lewisham.gov.uk'),
  ('Lichfield Council', 'licensing@lichfielddc.gov.uk'),
  ('Lincoln Council', 'licensing@lincoln.gov.uk'),
  ('Liverpool Council', 'licensing@liverpool.gov.uk'),
  ('London Borough of Merton', 'licensing@merton.gov.uk'),
  ('London Borough of Sutton', 'licensing@sutton.gov.uk'),
  ('Luton Council', 'licensing@luton.gov.uk'),
  ('Maidstone Council', 'licensing@maidstone.gov.uk'),
  ('Malden Council', 'licensing@maldon.gov.uk'),
  ('Malvern Hills Council', 'enquiries@worcsregservices.gov.uk'),
  ('Manchester Council', 'premises.licensing@manchester.gov.uk'),
  ('Mansfield Council', 'environmentallicensing@mansfield.gov.uk'),
  ('Medway Council', 'licensing@medway.gov.uk'),
  ('Melton Council', 'licensing@melton.gov.uk'),
  ('Mendip District Council', 'customerservices@mendip.gov.uk'),
  ('Mid Devon District Council', 'licensing@middevon.gov.uk'),
  ('Mid Suffolk Council', 'Licensing@midsuffolk.gov.uk'),
  ('Mid Sussex Council', 'licensing@midsussex.gov.uk'),
  ('Middlesbrough Council', 'licensing@middlesbrough.gov.uk'),
  ('Milton Keynes Council', 'licensing@milton-keynes.gov.uk'),
  ('Monmouthshire Council', 'licensing@monmouthshire.gov.uk'),
  ('Neath Port Talbot Council', 'licensing@npt.gov.uk'),
  ('New Forest Council', 'licensing@nfdc.gov.uk'),
  ('Newark & Sherwood Council', 'request@nsdc.inforequest@nsdc.info'),
  ('Newcastle Council', 'licensing@newcastle.gov.uk'),
  ('Newcastle under Lyme Borough Council', 'licensing@newcastle-staffs.gov.uk'),
  ('Newcastle under Lyme Council', 'licensing@newcastle-staffs.gov.uk'),
  ('Newham Council', 'licensingregistration@newham.gov.uk'),
  ('Newport Council', 'environment.licensing@newport.gov.uk'),
  ('North Devon Council', 'customerservices@northdevon.gov.uk'),
  ('North Dorset Council', 'envlicens@north-dorset.gov.uk'),
  ('North East Lincolnshire Council', 'licensing@nelincs.gov.uk'),
  ('North East Lincs Council', 'licensing@nelincs.gov.uk'),
  ('North Hertfordshire Council', 'licensing@north-herts.gov.uk'),
  ('North Herts Council', 'service@north-herts.gov.uk'),
  ('North Kesteven: Council', 'licensing@n-kesteven.gov.uk'),
  ('North Lincolnshire Council', 'customerservice@northlincs.gov.uk'),
  ('North Norfolk Council', 'licensing@north-norfolk.gov.uk'),
  ('North Somerset Council', 'licensing@n-somerset.gov.uk'),
  ('North Tyneside Council', 'liquor.licensing@northtyneside.gov.uk'),
  ('North Warwickshire Council', 'customerservices@northwarks.gov.uk'),
  ('North West Council', 'licensing@nwleicestershire.gov.uk'),
  ('North West Leicestershire Council', 'licensinglicensing@nwleicestershire.gov.uk'),
  ('Northampton Council', 'licensing@northampton.gov.uk'),
  ('Northumberland Council', 'licensing@northumberland.gov.uk'),
  ('Norwich Council', 'licensing@norwich.gov.uk'),
  ('Nottingham Council', 'general.licensing@nottinghamcity.gov.uk'),
  ('Oadby and Wigston Council', 'licensing@oadby-wigston.gov.uk'),
  ('Oldham Council', 'licensing@oldham.gov.uk'),
  ('Oxford Council', 'licensing@oxford.gov.uk'),
  ('Pembrokeshire Council', 'licensing@pembrokeshire.gov.uk'),
  ('Pendle Council', 'dls@pendle.gov.uk'),
  ('Peterborough', 'eh.licensing@Peterborough.gov.uk'),
  ('Plymouth Council', 'licensing@plymouth.gov.uk'),
  ('Portsmouth Council', 'licensing@portsmouthcc.gov.uk'),
  ('Powys Council', 'public.protection@powys.gov.uk'),
  ('Preston Council', 'licensing@preston.gov.uk'),
  ('Reading Council', 'licensing@reading.gov.uk'),
  ('Redbridge Council', 'Licensing.Authority@redbridge.gov.uk'),
  ('Redcar & Cleveland Borough Council', 'licensing_admin@redcar-cleveland.gov.uk'),
  ('Redditch Council', 'enquiries@worcsregservices.gov.uk'),
  ('Reigate Council', 'licensing@reigate-banstead.gov.uk'),
  ('Rhondda Council', 'Licensing.Section@rhondda-cynon-taff.gov.uk'),
  ('Richmond Upon Thames (London Borough)', 'licensing@richmond.gov.uk'),
  ('Richmondshire Council', 'licensing@richmondshire.gov.uk'),
  ('Rochdale Council', 'licensing.reg@rochdale.gov.uk'),
  ('Rochford Council', 'licensing@rochford.gov.uk'),
  ('Rossendale Borough Council', 'licensing@rossendalebc.gov.uk'),
  ('Rotherham Council', 'licensing@rotherham.gov.uk'),
  ('Rugby Council', 'licensing@rugby.gov.uk'),
  ('Runnymede Borough Council', 'licensing@runnymede.gov.uk'),
  ('Rushcliffe Borough Council', 'licensing@rushcliffe.gov.uk'),
  ('Rushmoor Council', 'licensing@rushmoor.gov.uk'),
  ('Rutland County Council', 'enquiries@rutland.gov.uk'),
  ('Ryedale Council', 'environmentalhealth@ryedale.gov.uk'),
  ('Salford Council', 'licensing@salford.gov.uk'),
  ('Sandwell Council', 'licensing_team@sandwell.gov.uk'),
  ('Scarborough', 'licensing.services@scarborough.gov.uk'),
  ('Sedgemoor Council', 'customer.services@sedgemoor.gov.uk'),
  ('Sefton Council', 'Licensing@sefton.gov.uk'),
  ('Selby Council', 'licensingsection@selby.gov.uk'),
  ('Sevenoaks Council', 'licensing@sevenoaks.gov.uk'),
  ('Sheffield Council', 'licensingservice@sheffield.gov.uk'),
  ('Shepway Council', 'licensing@shepway.gov.uk'),
  ('Shropshire Council', 'licensing@shropshire.gov.uk'),
  ('Slough Council', 'licensing@slough.gov.uk'),
  ('Solihull Council', 'licensing@solihull.gov.uk'),
  ('Somerset Council', 'licensing@southsomerset.gov.uk'),
  ('South Bucks District Council', 'licensing@SouthBucks.Gov.uk licensing@SouthBucks.Gov.uk'),
  ('South Cambs District Council', 'licensing@scambs.gov.uk'),
  ('South Derbyshire Council', 'licensing@southderbyshire.gov.uk'),
  ('South Gloucestershire Council', 'licensing@southglos.gov.uk'),
  ('South Hams Council', 'licensing@southhams.gov.uk'),
  ('South Holland Council', 'licensing@sholland.gov.uk'),
  ('South Kesteven District Council', 'licensing@southkesteven.gov.uk'),
  ('South Lakeland Council', 'licensing@southlakeland.gov.uk'),
  ('South Lanarkshire Council', 'licensing@southlanarkshire.gov.uk'),
  ('South Norfolk Council', 'licensingteam@s-norfolk.gov.uk'),
  ('South Northamptonshire Council', 'licensing@southnorthants.gov.uk'),
  ('South Ribble Council', 'licensing@southribble.gov.uk'),
  ('South Tyneside Council', 'Licensing@southtyneside.gov.uk'),
  ('Southampton Council', 'licensing@southampton.gov.uk'),
  ('Southend on Sea Council', 'council@southend.gov.uk'),
  ('Southwark Council', 'licensing@southwark.gov.uk'),
  ('Spelthorne Council', 'environmental.health.commercial@spelthorne.gov.uk'),
  ('St Albans Council', 'licensing@stalbans.gov.uk'),
  ('St Edmundsbury Council', 'licensing@stedsbc.gov.uk'),
  ('St Helens Council', 'generallicensing@sthelens.gov.uk'),
  ('Stafford Council', 'ehlicensing@staffordbc.gov.uk'),
  ('Staffordshire Moorlands Council', 'licensing@staffsmoorlands.gov.uk'),
  ('Stevenage Council', 'licensing@stevenage.gov.uk'),
  ('Stockport Council', 'licensing2003@stockport.gov.uk'),
  ('Stockton Council', 'licensing.administration@stockton.gov.uk'),
  ('Stoke on Trent City Council', 'stoke.go.ukhcp.licensing@stoke.gov.uk'),
  ('Stratford on Avon Council', 'licensing@stratford-dc.gov.uk'),
  ('Stroud Council', 'licensing@stroud.gov.uk'),
  ('Suffolk Council', 'licensing@suffolkcoastal.gov.uk'),
  ('Sunderland Council', '11838licensing@sunderland.gov.uk'),
  ('Swale Council', 'licensing@swale.gov.uk'),
  ('Swansea Council', 'evh.licensing@swansea.gov.uk'),
  ('Swindon Council', 'licensing@swindon.gov.uk'),
  ('Tameside Council', 'licensing@tameside.gov.uk'),
  ('Tamworth Council', 'publicprotection@tamworth.gov.uk'),
  ('Tandridge District Council', 'eh@tandridge.gov.uk'),
  ('Taunton Council', 'licensing@tauntondeane.gov.uk'),
  ('Telford & Wrekin Council', 'licensing@telford.gov.uk'),
  ('Tendring Council', 'licensingsection@tendringdc.gov.uk'),
  ('Tewsbury Council', 'licensing@tewkesbury.gov.uk'),
  ('Thanet Council', 'licensing@thanet.gov.uk'),
  ('Thurrock Council', 'licensing@thurrock.gov.uk'),
  ('Tonbridge & Malling Council', 'licensing.services@tmbc.gov.uk'),
  ('Torbay Council', 'licensing@torbay.gov.uk'),
  ('Torfaen (wales nr Pontypool) Council', 'licensing@torfaen.gov.uk'),
  ('Torridge Council', 'licensing@torridge.gov.uk'),
  ('Tower Hamlets Council', 'licensing@towerhamlets.gov.uk'),
  ('Trafford Council', 'licensing@trafford.gov.uk'),
  ('Uttlesford Council', 'licensing@uttlesford.gov.uk'),
  ('Vale of Glamorgan Council', 'Licensing@valeofglamorgan.gov.uk'),
  ('Vale of White Horse District Council', 'licensing.unit@whitehorsedc.gov.uk'),
  ('Wakefield Council', 'LicensingOffice@wakefield.gov.uk'),
  ('Walsall Council', 'licensing@walsall.gov.uk'),
  ('Waltham Forest Council', 'licensing@walthamforest.gov.uk'),
  ('Wandsworth Council', 'licensing@wandsworth.gov.uk'),
  ('Warrington Council', 'cexlicensing@warrington.gov.uk'),
  ('Warwick Council', 'licensing@warwickdc.gov.uk'),
  ('Watford Council', 'licensing@watford.gov.uk'),
  ('Waveney Council', 'licensing@waveney.gov.uk'),
  ('Waverley Council', 'licensing.policy@waverley.gov.uk'),
  ('Wealden Council', 'licensing@wealden.gov.uk'),
  ('Welwyn Council', 'licensing@welhat.gov.uk'),
  ('West Berkshire Council', 'licensing@westberks.gov.uk'),
  ('West Devon Council', 'licensing@westdevon.gov.uk'),
  ('West Dorset Council', 'licensing@westdorset-dc.gov.uk'),
  ('West Lancashire Council', 'licensing.enquiries@westlancs.gov.uk'),
  ('West Lindsey Council', 'licensing.2003@west-lindsey.gov.uk'),
  ('West Oxfordshire Council', 'community.services@westoxon.gov.uk'),
  ('West Suffolk Council', 'licensing@westsuffolk.gov.uk'),
  ('West Sussex City Council', 'registration.chichester@westsussex.gov.uk'),
  ('Westminster (City of) Council', 'premiseslicensing@westminster.gov.uk'),
  ('Weymouth & Portland Council', 'licensing@weymouth.gov.uk'),
  ('Wigan Council', 'Licensingact2003@wigan.gov.uk'),
  ('Wiltshire (4 diff offices, north, south, east, west) Council', 'publicprotectioneast@wiltshire.gov.uk'),
  ('Winchester 01962 848239 Council', 'licensing@winchester.gov.uk'),
  ('Windsor & Maidenhead Council', 'licensing@rbwm.gov.uk'),
  ('Wirral Council', 'licensing@wirral.gov.uk'),
  ('Woking Council', 'licensing@woking.gov.uk'),
  ('Wokingham Council', 'licensing@wokingham.gov.uk'),
  ('Wolverhampton Council', 'licensing@wolverhampton.gov.uk'),
  ('Worcester City Council', 'wrsenquiries@worcsregservices.gov.uk'),
  ('Worthing Council', 'licensing.unit@adur-worthing.gov.uk'),
  ('Wrexham Council', 'licensing@wrexham.gov.uk'),
  ('Wychavon Council', 'licensing@wychavon.gov.uk'),
  ('Wycombe Council', 'licensing@wycombe.gov.uk'),
  ('Wycombe District Council', 'licensing@wycombe.gov.uk'),
  ('Wyre Borough Council', 'enquiries@worcsregservices.gov.uk'),
  ('Wyre Forest District Council', 'licensing@wyreforestdc.gov.uk'),
  ('York Council', 'licensing.unit@york.gov.uk')
) AS d(org_name, email)
WHERE o.name = d.org_name
ON CONFLICT (organization_id, slug) DO UPDATE
  SET email = EXCLUDED.email,
      updated_at = NOW();

-- ============================================================================
-- VERIFICATION QUERY
-- ============================================================================
-- Run this to verify the import:
--
-- SELECT
--   o.name AS council_name,
--   d.name AS department_name,
--   d.email,
--   d.type
-- FROM departments d
-- JOIN organizations o ON d.organization_id = o.id
-- WHERE d.type = 'licensing'
-- ORDER BY o.name;
--
-- Expected result: 344 rows
-- ============================================================================

-- Create index for faster council lookups
CREATE INDEX IF NOT EXISTS idx_departments_org_type
  ON public.departments(organization_id, type);

CREATE INDEX IF NOT EXISTS idx_organizations_name
  ON public.organizations(name);

-- Full-text search on organization names
CREATE INDEX IF NOT EXISTS idx_organizations_name_search
  ON public.organizations
  USING GIN(to_tsvector('english', name));

COMMENT ON INDEX idx_organizations_name_search IS
  'Full-text search index for council name autocomplete';
